<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="D20Tek.Functional.AspNetCore" />
    <PackageReference Include="LowDb.Net" />
    <PackageReference Include="LowDb.Net.Repositories" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\D20Tek.MinimalApi.DevView\D20Tek.MinimalApi.DevView.csproj" />
  </ItemGroup>

</Project>
